// 디자인 토큰: 의미 기반으로 Tailwind 클래스 문자열을 관리한다.
export const tokens = {
  spacing: {
    screenX: "px-6",
    screenTop: "pt-6",
    contentX: "px-16",
    contentTop: "pt-16",
    sectionGap: "mb-6",
    titleGap: "mb-2",
    subtitleTop: "mt-8",
    subtitleBottom: "mb-24",
    cardTitleGap: "mb-8",
    footerTop: "pt-4",
    contentGap: "mb-4",
    choiceTop: "mt-6",
    chipGap: "mr-8 mb-8",
    summaryRowGap: "mb-12",
    summaryLabelGap: "mb-4",
    dotGap: "mr-2",
    ctaGap: "mr-3",
    toggleGap: "mr-4",
    bottomNavIconGap: "mb-4",
    navPaddingX: "px-8",
    listItemPaddingX: "px-16",
    listItemPaddingY: "py-12",
    listItemDescTop: "mt-4",
    listItemRightGap: "ml-12",
    inputPaddingX: "px-12",
    inputPaddingY: "py-10",
    inputLabelBottom: "mb-6",
    inputHelperTop: "mt-6",
    chipPaddingX: "px-12",
    chipPaddingY: "py-6",
    buttonPaddingMd: "py-12",
    buttonPaddingLg: "py-16",
    cardPadding: "p-16",
  },
  radius: {
    md: "rounded-md",
    full: "rounded-full",
  },
  color: {
    screen: "bg-bg-screen",
    surface: "bg-white",
    card: "bg-bg-card",
    primary: "bg-primary-500",
    primarySoft: "bg-primary-100",
    border: "border-border",
    borderPrimary: "border-primary-500",
    textPrimary: "text-text-primary",
    textSecondary: "text-text-secondary",
    textDisabled: "text-text-disabled",
    textOnPrimary: "text-bg-card",
    textBrand: "text-primary-500",
    dot: "bg-slate-200",
    dotActive: "bg-blue-500",
    transparent: "bg-transparent",
  },
  typography: {
    fontBase: "font-sans",
    titleLg: "text-title-lg",
    titleMd: "text-title-md",
    bodyMd: "text-body-md",
    bodySm: "text-body-sm",
    caption: "text-caption",
    weightBold: "font-bold",
    weightSemibold: "font-semibold",
  },
  layout: {
    rowCenter: "flex-row items-center",
    rowBetween: "flex-row items-center justify-between",
    center: "items-center justify-center",
    full: "flex-1",
  },
  size: {
    dot: "h-2 w-2",
    headerSlot: "w-32",
  },
  shadow: {
    sm: "shadow-sm",
  },
  opacity: {
    pressed: "opacity-60",
    disabled: "opacity-50",
  },
  border: {
    base: "border",
    top: "border-t",
    bottom: "border-b",
  },
};
